name = "puzzle_05"
description = "Advent of Code 2022 - Puzzle #5"
version = "0.1.0-dev"

authors = ["William J. Franck"]
maintainers = ["William J. Franck <william@sterna.io>"]
maintainers-logins = ["captain-haddock17"]

executables = ["puzzle_05"]

[build-switches]
"*".Ada_Version = "Ada2022"
# "*".style_checks = ["-gnatyM120"]